- name: Copy mongo repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
- name: install mongoDB
    ansible.builtin.yum:
      name: mongodb-org
      state: installed
- name: Start mongodb and enable service 
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
- name: Replace listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
- name: Restart mongodb service
    ansible.builtin.service:
      name: mongod
      state: restarted
