  - name: Copy mongo repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb-org-shell
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: load {{component}} data
    ansible.builtin.command: "mongo --host mongodb.kirandevops.online < /app/schema/{{component}}.js"
  